title: "Jiyoon Shin"
description: "3D Vision · Medical Imaging · Reliable AI"
url: "https://jiyoonshinkau.github.io"
baseurl: ""
remote_theme: piharpi/jekyll-klise

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

header_pages:
  - about.md
  - research.md
  - publications.md
  - teaching.md

author:
  name: "Jiyoon Shin"
  email: "jiyoonshin@kau.ac.kr"
  github: "jiyoonshinkau"

lang: ko
theme_color: auto
paginate: 6
show_excerpts: true

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

google_analytics:
disqus:
